version: "3.9"

services:
  database:
    image: 'postgres:latest'
    restart: unless-stopped
    ports:
      - 5432:5432
    env_file:
      - ./express/.env
    volumes:
      - ./db-data/:/var/lib/postgresql/data/

  backend:
    depends_on:
      - database
    container_name: backend
    restart: unless-stopped
    build:
      context: ./express
      dockerfile: Dockerfile
      target: base
    env_file:
      - ./express/.env
    ports:
      - "3001:3001"
    volumes:
      - ./express:/usr/src/app
      - ./express/node_modules:/usr/src/app/node_modules

  frontend:
    container_name: frontend
    restart: unless-stopped
    build:
      context: ./react
      dockerfile: Dockerfile
      target: base
    ports:
      - "3000:3000"
    volumes:
      - ./react:/usr/src/app
